// Generated by scripts/generate.mjs — do not edit by hand.
import { createBrand } from '../create-brand.js'

/** Google, monochrome — inherits `color` like every other icon. */
export const GoogleIcon = createBrand('icon-google', [
  {
    d: 'M23.52 12.27c0-.79-.07-1.54-.2-2.27H12v4.51h6.47a5.54 5.54 0 0 1-2.4 3.63v3h3.88c2.27-2.09 3.57-5.17 3.57-8.87Z',
  },
  {
    d: 'M12 24c3.24 0 5.96-1.08 7.95-2.91l-3.88-3.01c-1.08.72-2.45 1.15-4.07 1.15-3.13 0-5.78-2.11-6.73-4.96h-4v3.11A12 12 0 0 0 12 24Z',
  },
  {
    d: 'M5.27 14.27a7.2 7.2 0 0 1 0-4.54v-3.1h-4a12 12 0 0 0 0 10.75l4-3.11Z',
  },
  {
    d: 'M12 4.75c1.77 0 3.35.61 4.6 1.8l3.44-3.44C17.95 1.18 15.24 0 12 0A12 12 0 0 0 1.28 6.63l4 3.1c.94-2.85 3.59-4.98 6.72-4.98Z',
  },
])

/** Google in its official multi-colour palette, for sign-in buttons. */
export const GoogleColorIcon = createBrand('icon-google-color', [
  {
    d: 'M23.52 12.27c0-.79-.07-1.54-.2-2.27H12v4.51h6.47a5.54 5.54 0 0 1-2.4 3.63v3h3.88c2.27-2.09 3.57-5.17 3.57-8.87Z',
    fill: '#4285F4',
  },
  {
    d: 'M12 24c3.24 0 5.96-1.08 7.95-2.91l-3.88-3.01c-1.08.72-2.45 1.15-4.07 1.15-3.13 0-5.78-2.11-6.73-4.96h-4v3.11A12 12 0 0 0 12 24Z',
    fill: '#34A853',
  },
  {
    d: 'M5.27 14.27a7.2 7.2 0 0 1 0-4.54v-3.1h-4a12 12 0 0 0 0 10.75l4-3.11Z',
    fill: '#FBBC05',
  },
  {
    d: 'M12 4.75c1.77 0 3.35.61 4.6 1.8l3.44-3.44C17.95 1.18 15.24 0 12 0A12 12 0 0 0 1.28 6.63l4 3.1c.94-2.85 3.59-4.98 6.72-4.98Z',
    fill: '#EA4335',
  },
])
