// Generated by scripts/generate.mjs — do not edit by hand.
import { createBrand } from '../create-brand.js'

/** Microsoft, monochrome — inherits `color` like every other icon. */
export const MicrosoftIcon = createBrand('icon-microsoft', [
  {
    d: 'M1 1h10.2v10.2H1V1Z',
  },
  {
    d: 'M12.8 1H23v10.2H12.8V1Z',
  },
  {
    d: 'M1 12.8h10.2V23H1V12.8Z',
  },
  {
    d: 'M12.8 12.8H23V23H12.8V12.8Z',
  },
])

/** Microsoft in its official multi-colour palette, for sign-in buttons. */
export const MicrosoftColorIcon = createBrand('icon-microsoft-color', [
  {
    d: 'M1 1h10.2v10.2H1V1Z',
    fill: '#F25022',
  },
  {
    d: 'M12.8 1H23v10.2H12.8V1Z',
    fill: '#7FBA00',
  },
  {
    d: 'M1 12.8h10.2V23H1V12.8Z',
    fill: '#00A4EF',
  },
  {
    d: 'M12.8 12.8H23V23H12.8V12.8Z',
    fill: '#FFB900',
  },
])
