// Generated by scripts/generate.mjs — do not edit by hand.
import { createBrand } from '../create-brand.js'

/** X, monochrome — inherits `color` like every other icon. */
export const XSocialIcon = createBrand('icon-x', [
  {
    d: 'M14.234 10.162 22.977 0h-2.072l-7.591 8.824L7.251 0H.258l9.168 13.343L.258 24H2.33l8.016-9.318L16.749 24h6.993zm-2.837 3.299-.929-1.329L3.076 1.56h3.182l5.965 8.532.929 1.329 7.754 11.09h-3.182z',
  },
])

/**
 * X — the mark has no colour: black on light grounds, white on dark
 * ones, which is what `color` already does. Same drawing as `XSocialIcon`,
 * kept so every brand answers to the same pair of names.
 */
export const XSocialColorIcon = createBrand('icon-x-color', [
  {
    d: 'M14.234 10.162 22.977 0h-2.072l-7.591 8.824L7.251 0H.258l9.168 13.343L.258 24H2.33l8.016-9.318L16.749 24h6.993zm-2.837 3.299-.929-1.329L3.076 1.56h3.182l5.965 8.532.929 1.329 7.754 11.09h-3.182z',
  },
])
