// Generated by scripts/generate.mjs — do not edit by hand.
import { Accessibility } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AccessibilityIcon = createIcon('icon-accessibility', Accessibility)
