// Generated by scripts/generate.mjs — do not edit by hand.
import { Screencast } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AirplayIcon = createIcon('icon-airplay', Screencast)
