// Generated by scripts/generate.mjs — do not edit by hand.
import { Alarm } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AlarmClockIcon = createIcon('icon-alarm-clock', Alarm)
