// Generated by scripts/generate.mjs — do not edit by hand.
import { Album } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AlbumIcon = createIcon('icon-album', Album)
