// Generated by scripts/generate.mjs — do not edit by hand.
import { DangerCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AlertCircleIcon = createIcon('icon-alert-circle', DangerCircle)
