// Generated by scripts/generate.mjs — do not edit by hand.
import { DangerTriangle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AlertTriangleIcon = createIcon(
  'icon-alert-triangle',
  DangerTriangle,
)
