// Generated by scripts/generate.mjs — do not edit by hand.
import { AlignVerticalCenter } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AlignCenterVerticalIcon = createIcon(
  'icon-align-center-vertical',
  AlignVerticalCenter,
)
