// Generated by scripts/generate.mjs — do not edit by hand.
import { AlignHorizontalCenter } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AlignCenterHorizontalIcon = createIcon(
  'icon-align-center-horizontal',
  AlignHorizontalCenter,
)
