// Generated by scripts/generate.mjs — do not edit by hand.
import { AlignLeft } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AlignLeftIcon = createIcon('icon-align-left', AlignLeft)
