// Generated by scripts/generate.mjs — do not edit by hand.
import { AlignRight } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AlignRightIcon = createIcon('icon-align-right', AlignRight)
