// Generated by scripts/generate.mjs — do not edit by hand.
import { Archive } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArchiveIcon = createIcon('icon-archive', Archive)
