// Generated by scripts/generate.mjs — do not edit by hand.
import { Armchair } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArmchairIcon = createIcon('icon-armchair', Armchair)
