// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowRight } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowRightSquareIcon = createIcon(
  'icon-arrow-right-square',
  SquareArrowRight,
)
