// Generated by scripts/generate.mjs — do not edit by hand.
import { ArrowRightDown } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowDownRightIcon = createIcon(
  'icon-arrow-down-right',
  ArrowRightDown,
)
