// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowRightUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowUpRightSquareIcon = createIcon(
  'icon-arrow-up-right-square',
  SquareArrowRightUp,
)
