// Generated by scripts/generate.mjs — do not edit by hand.
import { ArrowLeftUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowUpLeftIcon = createIcon('icon-arrow-up-left', ArrowLeftUp)
