// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowUpSquareIcon = createIcon(
  'icon-arrow-up-square',
  SquareArrowUp,
)
