// Generated by scripts/generate.mjs — do not edit by hand.
import { TransferVertical } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowUpDownIcon = createIcon(
  'icon-arrow-up-down',
  TransferVertical,
)
