// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowLeftDown } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowDownLeftSquareIcon = createIcon(
  'icon-arrow-down-left-square',
  SquareArrowLeftDown,
)
