// Generated by scripts/generate.mjs — do not edit by hand.
import { ArrowLeftDown } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowDownLeftIcon = createIcon(
  'icon-arrow-down-left',
  ArrowLeftDown,
)
