// Generated by scripts/generate.mjs — do not edit by hand.
import { MentionCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AtSignIcon = createIcon('icon-at-sign', MentionCircle)
