// Generated by scripts/generate.mjs — do not edit by hand.
import { Atom } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AtomIcon = createIcon('icon-atom', Atom)
