// Generated by scripts/generate.mjs — do not edit by hand.
import { MedalStar } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const AwardIcon = createIcon('icon-award', MedalStar)
