// Generated by scripts/generate.mjs — do not edit by hand.
import { VerifiedCheck } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BadgeCheckIcon = createIcon('icon-badge-check', VerifiedCheck)
