// Generated by scripts/generate.mjs — do not edit by hand.
import { Banknote2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BanknoteIcon = createIcon('icon-banknote', Banknote2)
