// Generated by scripts/generate.mjs — do not edit by hand.
import { Bath } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BathIcon = createIcon('icon-bath', Bath)
