// Generated by scripts/generate.mjs — do not edit by hand.
import { BatteryLow } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BatteryLowIcon = createIcon('icon-battery-low', BatteryLow)
