// Generated by scripts/generate.mjs — do not edit by hand.
import { BatteryFull } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BatteryIcon = createIcon('icon-battery', BatteryFull)
