// Generated by scripts/generate.mjs — do not edit by hand.
import { Bicycling } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BikeIcon = createIcon('icon-bike', Bicycling)
