// Generated by scripts/generate.mjs — do not edit by hand.
import { TextBold } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BoldIcon = createIcon('icon-bold', TextBold)
