// Generated by scripts/generate.mjs — do not edit by hand.
import { Bolt } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BoltIcon = createIcon('icon-bolt', Bolt)
