// Generated by scripts/generate.mjs — do not edit by hand.
import { Bone } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BoneIcon = createIcon('icon-bone', Bone)
