// Generated by scripts/generate.mjs — do not edit by hand.
import { Box } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const BoxIcon = createIcon('icon-box', Box)
