// Generated by scripts/generate.mjs — do not edit by hand.
import { Buildings2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Building2Icon = createIcon('icon-building2', Buildings2)
