// Generated by scripts/generate.mjs — do not edit by hand.
import { Calculator } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CalculatorIcon = createIcon('icon-calculator', Calculator)
