// Generated by scripts/generate.mjs — do not edit by hand.
import { CalendarMark } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CalendarCheckIcon = createIcon('icon-calendar-check', CalendarMark)
