// Generated by scripts/generate.mjs — do not edit by hand.
import { CalendarAdd } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CalendarPlusIcon = createIcon('icon-calendar-plus', CalendarAdd)
