// Generated by scripts/generate.mjs — do not edit by hand.
import { CalendarSearch } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CalendarSearchIcon = createIcon(
  'icon-calendar-search',
  CalendarSearch,
)
