// Generated by scripts/generate.mjs — do not edit by hand.
import { SimCard } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CardSimIcon = createIcon('icon-card-sim', SimCard)
