// Generated by scripts/generate.mjs — do not edit by hand.
import { Screencast2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CastIcon = createIcon('icon-cast', Screencast2)
