// Generated by scripts/generate.mjs — do not edit by hand.
import { ChefHat } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ChefHatIcon = createIcon('icon-chef-hat', ChefHat)
