// Generated by scripts/generate.mjs — do not edit by hand.
import { DoubleAltArrowRight } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronsRightIcon = createIcon(
  'icon-chevrons-right',
  DoubleAltArrowRight,
)
