// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareAltArrowDown } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronDownSquareIcon = createIcon(
  'icon-chevron-down-square',
  SquareAltArrowDown,
)
