// Generated by scripts/generate.mjs — do not edit by hand.
import { DoubleAltArrowLeft } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronsLeftIcon = createIcon(
  'icon-chevrons-left',
  DoubleAltArrowLeft,
)
