// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareAltArrowRight } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronRightSquareIcon = createIcon(
  'icon-chevron-right-square',
  SquareAltArrowRight,
)
