// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareAltArrowLeft } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronLeftSquareIcon = createIcon(
  'icon-chevron-left-square',
  SquareAltArrowLeft,
)
