// Generated by scripts/generate.mjs — do not edit by hand.
import { DoubleAltArrowUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronsUpIcon = createIcon('icon-chevrons-up', DoubleAltArrowUp)
