// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundAltArrowUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronUpCircleIcon = createIcon(
  'icon-chevron-up-circle',
  RoundAltArrowUp,
)
