// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundArrowUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CircleArrowUpIcon = createIcon(
  'icon-circle-arrow-up',
  RoundArrowUp,
)
