// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundArrowDown } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CircleArrowDownIcon = createIcon(
  'icon-circle-arrow-down',
  RoundArrowDown,
)
