// Generated by scripts/generate.mjs — do not edit by hand.
import { PauseCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CirclePauseIcon = createIcon('icon-circle-pause', PauseCircle)
