// Generated by scripts/generate.mjs — do not edit by hand.
import { CheckCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CircleCheckBigIcon = createIcon(
  'icon-circle-check-big',
  CheckCircle,
)
