// Generated by scripts/generate.mjs — do not edit by hand.
import { StopCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CircleStopIcon = createIcon('icon-circle-stop', StopCircle)
