// Generated by scripts/generate.mjs — do not edit by hand.
import { MinusCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CircleMinusIcon = createIcon('icon-circle-minus', MinusCircle)
