// Generated by scripts/generate.mjs — do not edit by hand.
import { StarCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CircleStarIcon = createIcon('icon-circle-star', StarCircle)
