// Generated by scripts/generate.mjs — do not edit by hand.
import { UserCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CircleUserIcon = createIcon('icon-circle-user', UserCircle)
