// Generated by scripts/generate.mjs — do not edit by hand.
import { PlayCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CirclePlayIcon = createIcon('icon-circle-play', PlayCircle)
