// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundAltArrowUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CircleChevronUpIcon = createIcon(
  'icon-circle-chevron-up',
  RoundAltArrowUp,
)
