// Generated by scripts/generate.mjs — do not edit by hand.
import { ClipboardList } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ClipboardListIcon = createIcon(
  'icon-clipboard-list',
  ClipboardList,
)
