// Generated by scripts/generate.mjs — do not edit by hand.
import { CloudRain } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CloudRainIcon = createIcon('icon-cloud-rain', CloudRain)
