// Generated by scripts/generate.mjs — do not edit by hand.
import { CloudUpload } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CloudUploadIcon = createIcon('icon-cloud-upload', CloudUpload)
