// Generated by scripts/generate.mjs — do not edit by hand.
import { CloudCheck } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CloudCheckIcon = createIcon('icon-cloud-check', CloudCheck)
