// Generated by scripts/generate.mjs — do not edit by hand.
import { Code2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CodeXmlIcon = createIcon('icon-code-xml', Code2)
