// Generated by scripts/generate.mjs — do not edit by hand.
import { CodeSquare } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CodeSquareIcon = createIcon('icon-code-square', CodeSquare)
