// Generated by scripts/generate.mjs — do not edit by hand.
import { CreativeCommons } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CreativeCommonsIcon = createIcon(
  'icon-creative-commons',
  CreativeCommons,
)
