// Generated by scripts/generate.mjs — do not edit by hand.
import { Card } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const CreditCardIcon = createIcon('icon-credit-card', Card)
