// Generated by scripts/generate.mjs — do not edit by hand.
import { Database } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const DatabaseIcon = createIcon('icon-database', Database)
