// Generated by scripts/generate.mjs — do not edit by hand.
import { VinylRecord } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Disc3Icon = createIcon('icon-disc3', VinylRecord)
