// Generated by scripts/generate.mjs — do not edit by hand.
import { CloudDownload } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const DownloadCloudIcon = createIcon(
  'icon-download-cloud',
  CloudDownload,
)
