// Generated by scripts/generate.mjs — do not edit by hand.
import { Waterdrop } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const DropletIcon = createIcon('icon-droplet', Waterdrop)
