// Generated by scripts/generate.mjs — do not edit by hand.
import { Dumbbell } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const DumbbellIcon = createIcon('icon-dumbbell', Dumbbell)
