// Generated by scripts/generate.mjs — do not edit by hand.
import { Earth } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const EarthIcon = createIcon('icon-earth', Earth)
