// Generated by scripts/generate.mjs — do not edit by hand.
import { EyeClosed } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const EyeClosedIcon = createIcon('icon-eye-closed', EyeClosed)
