// Generated by scripts/generate.mjs — do not edit by hand.
import { RewindForward } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FastForwardIcon = createIcon('icon-fast-forward', RewindForward)
