// Generated by scripts/generate.mjs — do not edit by hand.
import { FerrisWheel } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FerrisWheelIcon = createIcon('icon-ferris-wheel', FerrisWheel)
