// Generated by scripts/generate.mjs — do not edit by hand.
import { FileCheck } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FileCheckIcon = createIcon('icon-file-check', FileCheck)
