// Generated by scripts/generate.mjs — do not edit by hand.
import { ZipFile } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FileArchiveIcon = createIcon('icon-file-archive', ZipFile)
