// Generated by scripts/generate.mjs — do not edit by hand.
import { CodeFile } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FileCodeIcon = createIcon('icon-file-code', CodeFile)
