// Generated by scripts/generate.mjs — do not edit by hand.
import { FileDownload } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FileDownIcon = createIcon('icon-file-down', FileDownload)
