// Generated by scripts/generate.mjs — do not edit by hand.
import { DocumentAdd } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FilePlusIcon = createIcon('icon-file-plus', DocumentAdd)
