// Generated by scripts/generate.mjs — do not edit by hand.
import { Fire } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FlameIcon = createIcon('icon-flame', Fire)
