// Generated by scripts/generate.mjs — do not edit by hand.
import { Flashlight } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FlashlightIcon = createIcon('icon-flashlight', Flashlight)
