// Generated by scripts/generate.mjs — do not edit by hand.
import { FlipVertical } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FlipVertical2Icon = createIcon('icon-flip-vertical2', FlipVertical)
