// Generated by scripts/generate.mjs — do not edit by hand.
import { FlipHorizontal } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FlipHorizontalIcon = createIcon(
  'icon-flip-horizontal',
  FlipHorizontal,
)
