// Generated by scripts/generate.mjs — do not edit by hand.
import { FolderOpen } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FolderOpenIcon = createIcon('icon-folder-open', FolderOpen)
