// Generated by scripts/generate.mjs — do not edit by hand.
import { AddFolder } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FolderPlusIcon = createIcon('icon-folder-plus', AddFolder)
