// Generated by scripts/generate.mjs — do not edit by hand.
import { FolderCheck } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const FolderCheckIcon = createIcon('icon-folder-check', FolderCheck)
