// Generated by scripts/generate.mjs — do not edit by hand.
import { Gamepad } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Gamepad2Icon = createIcon('icon-gamepad2', Gamepad)
