// Generated by scripts/generate.mjs — do not edit by hand.
import { Gamepad } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const GamepadIcon = createIcon('icon-gamepad', Gamepad)
