// Generated by scripts/generate.mjs — do not edit by hand.
import { SpeedometerMiddle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const GaugeIcon = createIcon('icon-gauge', SpeedometerMiddle)
