// Generated by scripts/generate.mjs — do not edit by hand.
import { BranchingPathsUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const GitBranchIcon = createIcon('icon-git-branch', BranchingPathsUp)
