// Generated by scripts/generate.mjs — do not edit by hand.
import { Global } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Globe2Icon = createIcon('icon-globe2', Global)
