// Generated by scripts/generate.mjs — do not edit by hand.
import { Reorder2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const GripVerticalIcon = createIcon('icon-grip-vertical', Reorder2)
