// Generated by scripts/generate.mjs — do not edit by hand.
import { HeartBroken } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const HeartCrackIcon = createIcon('icon-heart-crack', HeartBroken)
