// Generated by scripts/generate.mjs — do not edit by hand.
import { HeartPulse } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const HeartPulseIcon = createIcon('icon-heart-pulse', HeartPulse)
