// Generated by scripts/generate.mjs — do not edit by hand.
import { History } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const HistoryIcon = createIcon('icon-history', History)
