// Generated by scripts/generate.mjs — do not edit by hand.
import { Hospital } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const HospitalIcon = createIcon('icon-hospital', Hospital)
