// Generated by scripts/generate.mjs — do not edit by hand.
import { HourglassLine } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const HourglassIcon = createIcon('icon-hourglass', HourglassLine)
