// Generated by scripts/generate.mjs — do not edit by hand.
import { GalleryWide } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ImagesIcon = createIcon('icon-images', GalleryWide)
