// Generated by scripts/generate.mjs — do not edit by hand.
import { Inbox } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const InboxIcon = createIcon('icon-inbox', Inbox)
