// Generated by scripts/generate.mjs — do not edit by hand.
import { TextItalic } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ItalicIcon = createIcon('icon-italic', TextItalic)
