// Generated by scripts/generate.mjs — do not edit by hand.
import { Keyboard } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const KeyboardIcon = createIcon('icon-keyboard', Keyboard)
