// Generated by scripts/generate.mjs — do not edit by hand.
import { Layers } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Layers3Icon = createIcon('icon-layers3', Layers)
