// Generated by scripts/generate.mjs — do not edit by hand.
import { Library } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const LibraryIcon = createIcon('icon-library', Library)
