// Generated by scripts/generate.mjs — do not edit by hand.
import { Graph } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const LineChartIcon = createIcon('icon-line-chart', Graph)
