// Generated by scripts/generate.mjs — do not edit by hand.
import { LinkBroken } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Link2OffIcon = createIcon('icon-link2-off', LinkBroken)
