// Generated by scripts/generate.mjs — do not edit by hand.
import { ListCheck } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ListCheckIcon = createIcon('icon-list-check', ListCheck)
