// Generated by scripts/generate.mjs — do not edit by hand.
import { Filters } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ListFilterIcon = createIcon('icon-list-filter', Filters)
