// Generated by scripts/generate.mjs — do not edit by hand.
import { Playlist } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ListMusicIcon = createIcon('icon-list-music', Playlist)
