// Generated by scripts/generate.mjs — do not edit by hand.
import { MapPointRemove } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MapPinMinusIcon = createIcon('icon-map-pin-minus', MapPointRemove)
