// Generated by scripts/generate.mjs — do not edit by hand.
import { MapPointAdd } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MapPinPlusIcon = createIcon('icon-map-pin-plus', MapPointAdd)
