// Generated by scripts/generate.mjs — do not edit by hand.
import { Maximize } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Maximize2Icon = createIcon('icon-maximize2', Maximize)
