// Generated by scripts/generate.mjs — do not edit by hand.
import { ChatRoundDots } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MessageCircleMoreIcon = createIcon(
  'icon-message-circle-more',
  ChatRoundDots,
)
