// Generated by scripts/generate.mjs — do not edit by hand.
import { ChatSquare2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MessagesSquareIcon = createIcon(
  'icon-messages-square',
  ChatSquare2,
)
