// Generated by scripts/generate.mjs — do not edit by hand.
import { MinusSquare } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MinusSquareIcon = createIcon('icon-minus-square', MinusSquare)
