// Generated by scripts/generate.mjs — do not edit by hand.
import { Mirror } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MirrorRoundIcon = createIcon('icon-mirror-round', Mirror)
