// Generated by scripts/generate.mjs — do not edit by hand.
import { Monitor } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MonitorIcon = createIcon('icon-monitor', Monitor)
