// Generated by scripts/generate.mjs — do not edit by hand.
import { Devices } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MonitorSmartphoneIcon = createIcon(
  'icon-monitor-smartphone',
  Devices,
)
