// Generated by scripts/generate.mjs — do not edit by hand.
import { Mouse } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MouseIcon = createIcon('icon-mouse', Mouse)
