// Generated by scripts/generate.mjs — do not edit by hand.
import { TransferHorizontal } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MoveHorizontalIcon = createIcon(
  'icon-move-horizontal',
  TransferHorizontal,
)
