// Generated by scripts/generate.mjs — do not edit by hand.
import { MusicNote } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const MusicIcon = createIcon('icon-music', MusicNote)
