// Generated by scripts/generate.mjs — do not edit by hand.
import { MusicNote3 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Music3Icon = createIcon('icon-music3', MusicNote3)
