// Generated by scripts/generate.mjs — do not edit by hand.
import { MusicNote4 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Music4Icon = createIcon('icon-music4', MusicNote4)
