// Generated by scripts/generate.mjs — do not edit by hand.
import { MusicNote2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Music2Icon = createIcon('icon-music2', MusicNote2)
