// Generated by scripts/generate.mjs — do not edit by hand.
import { Notebook } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const NotebookIcon = createIcon('icon-notebook', Notebook)
