// Generated by scripts/generate.mjs — do not edit by hand.
import { PaintRoller } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PaintRollerIcon = createIcon('icon-paint-roller', PaintRoller)
