// Generated by scripts/generate.mjs — do not edit by hand.
import { Palette } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PaletteIcon = createIcon('icon-palette', Palette)
