// Generated by scripts/generate.mjs — do not edit by hand.
import { Paperclip2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PaperclipIcon = createIcon('icon-paperclip', Paperclip2)
