// Generated by scripts/generate.mjs — do not edit by hand.
import { Pause } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PauseIcon = createIcon('icon-pause', Pause)
