// Generated by scripts/generate.mjs — do not edit by hand.
import { Pen } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PenLineIcon = createIcon('icon-pen-line', Pen)
