// Generated by scripts/generate.mjs — do not edit by hand.
import { Pen } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PenIcon = createIcon('icon-pen', Pen)
