// Generated by scripts/generate.mjs — do not edit by hand.
import { Sale } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PercentIcon = createIcon('icon-percent', Sale)
