// Generated by scripts/generate.mjs — do not edit by hand.
import { EndCall } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PhoneOffIcon = createIcon('icon-phone-off', EndCall)
