// Generated by scripts/generate.mjs — do not edit by hand.
import { OutgoingCallRounded } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PhoneOutgoingIcon = createIcon(
  'icon-phone-outgoing',
  OutgoingCallRounded,
)
