// Generated by scripts/generate.mjs — do not edit by hand.
import { CallDropped } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PhoneMissedIcon = createIcon('icon-phone-missed', CallDropped)
