// Generated by scripts/generate.mjs — do not edit by hand.
import { PhoneCalling } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PhoneCallIcon = createIcon('icon-phone-call', PhoneCalling)
