// Generated by scripts/generate.mjs — do not edit by hand.
import { Pip2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PictureInPicture2Icon = createIcon(
  'icon-picture-in-picture2',
  Pip2,
)
