// Generated by scripts/generate.mjs — do not edit by hand.
import { Pip } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PictureInPictureIcon = createIcon('icon-picture-in-picture', Pip)
