// Generated by scripts/generate.mjs — do not edit by hand.
import { Pill } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PillIcon = createIcon('icon-pill', Pill)
