// Generated by scripts/generate.mjs — do not edit by hand.
import { Pin } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PinIcon = createIcon('icon-pin', Pin)
