// Generated by scripts/generate.mjs — do not edit by hand.
import { Dropper } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PipetteIcon = createIcon('icon-pipette', Dropper)
