// Generated by scripts/generate.mjs — do not edit by hand.
import { PlugCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Plug2Icon = createIcon('icon-plug2', PlugCircle)
