// Generated by scripts/generate.mjs — do not edit by hand.
import { SoundwaveCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PodcastIcon = createIcon('icon-podcast', SoundwaveCircle)
