// Generated by scripts/generate.mjs — do not edit by hand.
import { PresentationGraph } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const PresentationIcon = createIcon(
  'icon-presentation',
  PresentationGraph,
)
