// Generated by scripts/generate.mjs — do not edit by hand.
import { QrCode } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const QrCodeIcon = createIcon('icon-qr-code', QrCode)
