// Generated by scripts/generate.mjs — do not edit by hand.
import { Radar } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const RadarIcon = createIcon('icon-radar', Radar)
