// Generated by scripts/generate.mjs — do not edit by hand.
import { Bill } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ReceiptIcon = createIcon('icon-receipt', Bill)
