// Generated by scripts/generate.mjs — do not edit by hand.
import { UndoRightRound } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Redo2Icon = createIcon('icon-redo2', UndoRightRound)
