// Generated by scripts/generate.mjs — do not edit by hand.
import { RepeatOne } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Repeat1Icon = createIcon('icon-repeat1', RepeatOne)
