// Generated by scripts/generate.mjs — do not edit by hand.
import { Repeat } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Repeat2Icon = createIcon('icon-repeat2', Repeat)
