// Generated by scripts/generate.mjs — do not edit by hand.
import { Reply } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ReplyIcon = createIcon('icon-reply', Reply)
