// Generated by scripts/generate.mjs — do not edit by hand.
import { RefreshCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const RotateCwIcon = createIcon('icon-rotate-cw', RefreshCircle)
