// Generated by scripts/generate.mjs — do not edit by hand.
import { Restart } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const RotateCcwIcon = createIcon('icon-rotate-ccw', Restart)
