// Generated by scripts/generate.mjs — do not edit by hand.
import { Satellite } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SatelliteIcon = createIcon('icon-satellite', Satellite)
