// Generated by scripts/generate.mjs — do not edit by hand.
import { Scale } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ScaleIcon = createIcon('icon-scale', Scale)
