// Generated by scripts/generate.mjs — do not edit by hand.
import { Scissors } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ScissorsIcon = createIcon('icon-scissors', Scissors)
