// Generated by scripts/generate.mjs — do not edit by hand.
import { ScissorsSquare } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ScissorsSquareIcon = createIcon(
  'icon-scissors-square',
  ScissorsSquare,
)
