// Generated by scripts/generate.mjs — do not edit by hand.
import { ScreenShare } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ScreenShareIcon = createIcon('icon-screen-share', ScreenShare)
