// Generated by scripts/generate.mjs — do not edit by hand.
import { Server } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ServerIcon = createIcon('icon-server', Server)
