// Generated by scripts/generate.mjs — do not edit by hand.
import { SettingsMinimalistic } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Settings2Icon = createIcon('icon-settings2', SettingsMinimalistic)
