// Generated by scripts/generate.mjs — do not edit by hand.
import { Share } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ShareIcon = createIcon('icon-share', Share)
