// Generated by scripts/generate.mjs — do not edit by hand.
import { ShieldCross } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ShieldCloseIcon = createIcon('icon-shield-close', ShieldCross)
