// Generated by scripts/generate.mjs — do not edit by hand.
import { ShieldWarning } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ShieldAlertIcon = createIcon('icon-shield-alert', ShieldWarning)
