// Generated by scripts/generate.mjs — do not edit by hand.
import { ShieldMinus } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ShieldMinusIcon = createIcon('icon-shield-minus', ShieldMinus)
