// Generated by scripts/generate.mjs — do not edit by hand.
import { QuitFullScreen } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ShrinkIcon = createIcon('icon-shrink', QuitFullScreen)
