// Generated by scripts/generate.mjs — do not edit by hand.
import { Sidebar } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SidebarIcon = createIcon('icon-sidebar', Sidebar)
