// Generated by scripts/generate.mjs — do not edit by hand.
import { Signpost2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SignpostIcon = createIcon('icon-signpost', Signpost2)
