// Generated by scripts/generate.mjs — do not edit by hand.
import { Siren } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SirenIcon = createIcon('icon-siren', Siren)
