// Generated by scripts/generate.mjs — do not edit by hand.
import { SlashSquare } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SlashSquareIcon = createIcon('icon-slash-square', SlashSquare)
