// Generated by scripts/generate.mjs — do not edit by hand.
import { SlashCircle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SlashIcon = createIcon('icon-slash', SlashCircle)
