// Generated by scripts/generate.mjs — do not edit by hand.
import { Ladle } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SoupIcon = createIcon('icon-soup', Ladle)
