// Generated by scripts/generate.mjs — do not edit by hand.
import { Stars } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SparklesIcon = createIcon('icon-sparkles', Stars)
