// Generated by scripts/generate.mjs — do not edit by hand.
import { Speaker } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SpeakerIcon = createIcon('icon-speaker', Speaker)
