// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowRight } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SquareArrowRightIcon = createIcon(
  'icon-square-arrow-right',
  SquareArrowRight,
)
