// Generated by scripts/generate.mjs — do not edit by hand.
import { CheckSquare } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SquareCheckIcon = createIcon('icon-square-check', CheckSquare)
