// Generated by scripts/generate.mjs — do not edit by hand.
import { MinusSquare } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SquareMinusIcon = createIcon('icon-square-minus', MinusSquare)
