// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowRightDown } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SquareArrowDownRightIcon = createIcon(
  'icon-square-arrow-down-right',
  SquareArrowRightDown,
)
