// Generated by scripts/generate.mjs — do not edit by hand.
import { CloseSquare } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SquareXIcon = createIcon('icon-square-x', CloseSquare)
