// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowLeftDown } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SquareArrowDownLeftIcon = createIcon(
  'icon-square-arrow-down-left',
  SquareArrowLeftDown,
)
