// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowRightUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SquareArrowUpRightIcon = createIcon(
  'icon-square-arrow-up-right',
  SquareArrowRightUp,
)
