// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowLeftUp } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SquareArrowUpLeftIcon = createIcon(
  'icon-square-arrow-up-left',
  SquareArrowLeftUp,
)
