// Generated by scripts/generate.mjs — do not edit by hand.
import { Shop } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const StoreIcon = createIcon('icon-store', Shop)
