// Generated by scripts/generate.mjs — do not edit by hand.
import { TextCross } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const StrikethroughIcon = createIcon('icon-strikethrough', TextCross)
