// Generated by scripts/generate.mjs — do not edit by hand.
import { Sunrise } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SunriseIcon = createIcon('icon-sunrise', Sunrise)
