// Generated by scripts/generate.mjs — do not edit by hand.
import { Sunset } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const SunsetIcon = createIcon('icon-sunset', Sunset)
