// Generated by scripts/generate.mjs — do not edit by hand.
import { TestTube } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const TestTubeIcon = createIcon('icon-test-tube', TestTube)
