// Generated by scripts/generate.mjs — do not edit by hand.
import { TextSelection } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const TextSelectionIcon = createIcon(
  'icon-text-selection',
  TextSelection,
)
