// Generated by scripts/generate.mjs — do not edit by hand.
import { Ticket } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const TicketIcon = createIcon('icon-ticket', Ticket)
