// Generated by scripts/generate.mjs — do not edit by hand.
import { Tornado } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const TornadoIcon = createIcon('icon-tornado', Tornado)
