// Generated by scripts/generate.mjs — do not edit by hand.
import { Tram } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const TrainIcon = createIcon('icon-train', Tram)
