// Generated by scripts/generate.mjs — do not edit by hand.
import { Cup } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const TrophyIcon = createIcon('icon-trophy', Cup)
