// Generated by scripts/generate.mjs — do not edit by hand.
import { Delivery } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const TruckIcon = createIcon('icon-truck', Delivery)
