// Generated by scripts/generate.mjs — do not edit by hand.
import { Umbrella } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const UmbrellaIcon = createIcon('icon-umbrella', Umbrella)
