// Generated by scripts/generate.mjs — do not edit by hand.
import { UndoLeftRound } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Undo2Icon = createIcon('icon-undo2', UndoLeftRound)
