// Generated by scripts/generate.mjs — do not edit by hand.
import { User } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const User2Icon = createIcon('icon-user2', User)
