// Generated by scripts/generate.mjs — do not edit by hand.
import { UserPlus } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const UserRoundPlusIcon = createIcon('icon-user-round-plus', UserPlus)
