// Generated by scripts/generate.mjs — do not edit by hand.
import { UserCheck } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const UserRoundCheckIcon = createIcon('icon-user-round-check', UserCheck)
