// Generated by scripts/generate.mjs — do not edit by hand.
import { UserCheckRounded } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const UserCheckIcon = createIcon('icon-user-check', UserCheckRounded)
