// Generated by scripts/generate.mjs — do not edit by hand.
import { UserMinus } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const UserRoundMinusIcon = createIcon('icon-user-round-minus', UserMinus)
