// Generated by scripts/generate.mjs — do not edit by hand.
import { UserCheck } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const UserCheck2Icon = createIcon('icon-user-check2', UserCheck)
