// Generated by scripts/generate.mjs — do not edit by hand.
import { UserCrossRounded } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const UserXIcon = createIcon('icon-user-x', UserCrossRounded)
