// Generated by scripts/generate.mjs — do not edit by hand.
import { VolumeSmall } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Volume1Icon = createIcon('icon-volume1', VolumeSmall)
