// Generated by scripts/generate.mjs — do not edit by hand.
import { Wallet2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Wallet2Icon = createIcon('icon-wallet2', Wallet2)
