// Generated by scripts/generate.mjs — do not edit by hand.
import { MagicStick2 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const Wand2Icon = createIcon('icon-wand2', MagicStick2)
