// Generated by scripts/generate.mjs — do not edit by hand.
import { MagicStick3 } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const WandSparklesIcon = createIcon('icon-wand-sparkles', MagicStick3)
