// Generated by scripts/generate.mjs — do not edit by hand.
import { MagicStick } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const WandIcon = createIcon('icon-wand', MagicStick)
