// Generated by scripts/generate.mjs — do not edit by hand.
import { WashingMachine } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const WashingMachineIcon = createIcon(
  'icon-washing-machine',
  WashingMachine,
)
