// Generated by scripts/generate.mjs — do not edit by hand.
import { WatchRound } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const WatchIcon = createIcon('icon-watch', WatchRound)
