// Generated by scripts/generate.mjs — do not edit by hand.
import { WiFiRouter } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const WifiIcon = createIcon('icon-wifi', WiFiRouter)
