// Generated by scripts/generate.mjs — do not edit by hand.
import { MagniferZoomOut } from '@solar-icons/react-native/Outline'

import { createIcon } from '../create-icon.js'

export const ZoomOutIcon = createIcon('icon-zoom-out', MagniferZoomOut)
