// Generated by scripts/generate.mjs — do not edit by hand.
import { Pulse } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ActivityIcon = createIcon('icon-activity', Pulse)
