// Generated by scripts/generate.mjs — do not edit by hand.
import { DangerSquare } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const AlertOctagonIcon = createIcon('icon-alert-octagon', DangerSquare)
