// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundArrowRight } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowRightCircleIcon = createIcon(
  'icon-arrow-right-circle',
  RoundArrowRight,
)
