// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundArrowLeft } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowLeftCircleIcon = createIcon(
  'icon-arrow-left-circle',
  RoundArrowLeft,
)
