// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundArrowUp } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowUpCircleIcon = createIcon(
  'icon-arrow-up-circle',
  RoundArrowUp,
)
