// Generated by scripts/generate.mjs — do not edit by hand.
import { ArrowRightUp } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowUpRightIcon = createIcon('icon-arrow-up-right', ArrowRightUp)
