// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowRightDown } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowDownRightSquareIcon = createIcon(
  'icon-arrow-down-right-square',
  SquareArrowRightDown,
)
