// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowLeftUp } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowUpLeftSquareIcon = createIcon(
  'icon-arrow-up-left-square',
  SquareArrowLeftUp,
)
