// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundArrowDown } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowDownCircleIcon = createIcon(
  'icon-arrow-down-circle',
  RoundArrowDown,
)
