// Generated by scripts/generate.mjs — do not edit by hand.
import { TransferHorizontal } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowLeftRightIcon = createIcon(
  'icon-arrow-left-right',
  TransferHorizontal,
)
