// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowLeft } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ArrowLeftSquareIcon = createIcon(
  'icon-arrow-left-square',
  SquareArrowLeft,
)
