// Generated by scripts/generate.mjs — do not edit by hand.
import { Soundwave } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const AudioLinesIcon = createIcon('icon-audio-lines', Soundwave)
