// Generated by scripts/generate.mjs — do not edit by hand.
import { Backpack } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BackpackIcon = createIcon('icon-backpack', Backpack)
