// Generated by scripts/generate.mjs — do not edit by hand.
import { Forbidden } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BanIcon = createIcon('icon-ban', Forbidden)
