// Generated by scripts/generate.mjs — do not edit by hand.
import { BatteryHalf } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BatteryMediumIcon = createIcon('icon-battery-medium', BatteryHalf)
