// Generated by scripts/generate.mjs — do not edit by hand.
import { BatteryFull } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BatteryFullIcon = createIcon('icon-battery-full', BatteryFull)
