// Generated by scripts/generate.mjs — do not edit by hand.
import { Bed } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BedIcon = createIcon('icon-bed', Bed)
