// Generated by scripts/generate.mjs — do not edit by hand.
import { BellOff } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BellOffIcon = createIcon('icon-bell-off', BellOff)
