// Generated by scripts/generate.mjs — do not edit by hand.
import { BellBing } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BellRingIcon = createIcon('icon-bell-ring', BellBing)
