// Generated by scripts/generate.mjs — do not edit by hand.
import { Bluetooth } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BluetoothIcon = createIcon('icon-bluetooth', Bluetooth)
