// Generated by scripts/generate.mjs — do not edit by hand.
import { Bomb } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BombIcon = createIcon('icon-bomb', Bomb)
