// Generated by scripts/generate.mjs — do not edit by hand.
import { Bookmark } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BookmarkIcon = createIcon('icon-bookmark', Bookmark)
