// Generated by scripts/generate.mjs — do not edit by hand.
import { Book } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BookIcon = createIcon('icon-book', Book)
