// Generated by scripts/generate.mjs — do not edit by hand.
import { Case } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BriefcaseIcon = createIcon('icon-briefcase', Case)
