// Generated by scripts/generate.mjs — do not edit by hand.
import { Bug } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const BugIcon = createIcon('icon-bug', Bug)
