// Generated by scripts/generate.mjs — do not edit by hand.
import { Cat } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CatIcon = createIcon('icon-cat', Cat)
