// Generated by scripts/generate.mjs — do not edit by hand.
import { Graph } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ChartLineIcon = createIcon('icon-chart-line', Graph)
