// Generated by scripts/generate.mjs — do not edit by hand.
import { CheckSquare } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CheckSquare2Icon = createIcon('icon-check-square2', CheckSquare)
