// Generated by scripts/generate.mjs — do not edit by hand.
import { CheckCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CheckCheckIcon = createIcon('icon-check-check', CheckCircle)
