// Generated by scripts/generate.mjs — do not edit by hand.
import { CheckSquare } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CheckSquareIcon = createIcon('icon-check-square', CheckSquare)
