// Generated by scripts/generate.mjs — do not edit by hand.
import { DoubleAltArrowDown } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronsDownIcon = createIcon(
  'icon-chevrons-down',
  DoubleAltArrowDown,
)
