// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundAltArrowRight } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronRightCircleIcon = createIcon(
  'icon-chevron-right-circle',
  RoundAltArrowRight,
)
