// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundAltArrowDown } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronDownCircleIcon = createIcon(
  'icon-chevron-down-circle',
  RoundAltArrowDown,
)
