// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareAltArrowUp } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ChevronUpSquareIcon = createIcon(
  'icon-chevron-up-square',
  SquareAltArrowUp,
)
