// Generated by scripts/generate.mjs — do not edit by hand.
import { DangerCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CircleAlertIcon = createIcon('icon-circle-alert', DangerCircle)
