// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundAltArrowLeft } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CircleChevronLeftIcon = createIcon(
  'icon-circle-chevron-left',
  RoundAltArrowLeft,
)
