// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundArrowRight } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CircleArrowRightIcon = createIcon(
  'icon-circle-arrow-right',
  RoundArrowRight,
)
