// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundAltArrowRight } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CircleChevronRightIcon = createIcon(
  'icon-circle-chevron-right',
  RoundAltArrowRight,
)
