// Generated by scripts/generate.mjs — do not edit by hand.
import { RoundArrowRightUp } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CircleArrowOutUpRightIcon = createIcon(
  'icon-circle-arrow-out-up-right',
  RoundArrowRightUp,
)
