// Generated by scripts/generate.mjs — do not edit by hand.
import { ClockCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const Clock5Icon = createIcon('icon-clock5', ClockCircle)
