// Generated by scripts/generate.mjs — do not edit by hand.
import { CloudDownload } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CloudDownloadIcon = createIcon(
  'icon-cloud-download',
  CloudDownload,
)
