// Generated by scripts/generate.mjs — do not edit by hand.
import { CloudSun } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CloudSunIcon = createIcon('icon-cloud-sun', CloudSun)
