// Generated by scripts/generate.mjs — do not edit by hand.
import { Code } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CodeIcon = createIcon('icon-code', Code)
