// Generated by scripts/generate.mjs — do not edit by hand.
import { Code2 } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const Code2Icon = createIcon('icon-code2', Code2)
