// Generated by scripts/generate.mjs — do not edit by hand.
import { Command } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CommandIcon = createIcon('icon-command', Command)
