// Generated by scripts/generate.mjs — do not edit by hand.
import { UserId } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ContactIcon = createIcon('icon-contact', UserId)
