// Generated by scripts/generate.mjs — do not edit by hand.
import { Copyright } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CopyrightIcon = createIcon('icon-copyright', Copyright)
