// Generated by scripts/generate.mjs — do not edit by hand.
import { Cpu } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CpuIcon = createIcon('icon-cpu', Cpu)
