// Generated by scripts/generate.mjs — do not edit by hand.
import { Crop } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CropIcon = createIcon('icon-crop', Crop)
