// Generated by scripts/generate.mjs — do not edit by hand.
import { CloseCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const CrossIcon = createIcon('icon-cross', CloseCircle)
