// Generated by scripts/generate.mjs — do not edit by hand.
import { Vinyl } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const DiscIcon = createIcon('icon-disc', Vinyl)
