// Generated by scripts/generate.mjs — do not edit by hand.
import { Dna } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const DnaIcon = createIcon('icon-dna', Dna)
