// Generated by scripts/generate.mjs — do not edit by hand.
import { Dollar } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const DollarSignIcon = createIcon('icon-dollar-sign', Dollar)
