// Generated by scripts/generate.mjs — do not edit by hand.
import { Donut } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const DonutIcon = createIcon('icon-donut', Donut)
