// Generated by scripts/generate.mjs — do not edit by hand.
import { Waterdrops } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const DropletsIcon = createIcon('icon-droplets', Waterdrops)
