// Generated by scripts/generate.mjs — do not edit by hand.
import { Eraser } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const EraserIcon = createIcon('icon-eraser', Eraser)
