// Generated by scripts/generate.mjs — do not edit by hand.
import { Euro } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const EuroIcon = createIcon('icon-euro', Euro)
