// Generated by scripts/generate.mjs — do not edit by hand.
import { FullScreen } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ExpandIcon = createIcon('icon-expand', FullScreen)
