// Generated by scripts/generate.mjs — do not edit by hand.
import { Export } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ExternalLinkIcon = createIcon('icon-external-link', Export)
