// Generated by scripts/generate.mjs — do not edit by hand.
import { Figma } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FigmaIcon = createIcon('icon-figma', Figma)
