// Generated by scripts/generate.mjs — do not edit by hand.
import { FileText } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FileTextIcon = createIcon('icon-file-text', FileText)
