// Generated by scripts/generate.mjs — do not edit by hand.
import { FileCheck } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FileCheck2Icon = createIcon('icon-file-check2', FileCheck)
