// Generated by scripts/generate.mjs — do not edit by hand.
import { CodeFile } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FileCode2Icon = createIcon('icon-file-code2', CodeFile)
