// Generated by scripts/generate.mjs — do not edit by hand.
import { FileSend } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FileUpIcon = createIcon('icon-file-up', FileSend)
