// Generated by scripts/generate.mjs — do not edit by hand.
import { Clapperboard } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FilmIcon = createIcon('icon-film', Clapperboard)
