// Generated by scripts/generate.mjs — do not edit by hand.
import { Flag } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FlagIcon = createIcon('icon-flag', Flag)
