// Generated by scripts/generate.mjs — do not edit by hand.
import { FlipVertical } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FlipVerticalIcon = createIcon('icon-flip-vertical', FlipVertical)
