// Generated by scripts/generate.mjs — do not edit by hand.
import { FlipHorizontal } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FlipHorizontal2Icon = createIcon(
  'icon-flip-horizontal2',
  FlipHorizontal,
)
