// Generated by scripts/generate.mjs — do not edit by hand.
import { MoveToFolder } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const FolderInputIcon = createIcon('icon-folder-input', MoveToFolder)
