// Generated by scripts/generate.mjs — do not edit by hand.
import { Forward } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ForwardIcon = createIcon('icon-forward', Forward)
