// Generated by scripts/generate.mjs — do not edit by hand.
import { Glasses } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const GlassesIcon = createIcon('icon-glasses', Glasses)
