// Generated by scripts/generate.mjs — do not edit by hand.
import { MenuDots } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const GripHorizontalIcon = createIcon('icon-grip-horizontal', MenuDots)
