// Generated by scripts/generate.mjs — do not edit by hand.
import { HandHeart } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const HandHeartIcon = createIcon('icon-hand-heart', HandHeart)
