// Generated by scripts/generate.mjs — do not edit by hand.
import { SsdRound } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const HardDriveIcon = createIcon('icon-hard-drive', SsdRound)
