// Generated by scripts/generate.mjs — do not edit by hand.
import { Hashtag } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const HashIcon = createIcon('icon-hash', Hashtag)
