// Generated by scripts/generate.mjs — do not edit by hand.
import { Import } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ImportIcon = createIcon('icon-import', Import)
