// Generated by scripts/generate.mjs — do not edit by hand.
import { Infinity as SolarInfinity } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const InfinityIcon = createIcon('icon-infinity', SolarInfinity)
