// Generated by scripts/generate.mjs — do not edit by hand.
import { Key } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const KeyIcon = createIcon('icon-key', Key)
