// Generated by scripts/generate.mjs — do not edit by hand.
import { KeySquare } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const KeySquareIcon = createIcon('icon-key-square', KeySquare)
