// Generated by scripts/generate.mjs — do not edit by hand.
import { KeyMinimalistic } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const KeyRoundIcon = createIcon('icon-key-round', KeyMinimalistic)
