// Generated by scripts/generate.mjs — do not edit by hand.
import { Lamp } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const LampIcon = createIcon('icon-lamp', Lamp)
