// Generated by scripts/generate.mjs — do not edit by hand.
import { FloorLamp } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const LampFloorIcon = createIcon('icon-lamp-floor', FloorLamp)
