// Generated by scripts/generate.mjs — do not edit by hand.
import { Laptop } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const LaptopIcon = createIcon('icon-laptop', Laptop)
