// Generated by scripts/generate.mjs — do not edit by hand.
import { Laptop2 } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const Laptop2Icon = createIcon('icon-laptop2', Laptop2)
