// Generated by scripts/generate.mjs — do not edit by hand.
import { Layers } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const Layers2Icon = createIcon('icon-layers2', Layers)
