// Generated by scripts/generate.mjs — do not edit by hand.
import { Widget2 } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const LayoutGridIcon = createIcon('icon-layout-grid', Widget2)
