// Generated by scripts/generate.mjs — do not edit by hand.
import { Lightbulb } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const LightbulbIcon = createIcon('icon-lightbulb', Lightbulb)
