// Generated by scripts/generate.mjs — do not edit by hand.
import { Link } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const Link2Icon = createIcon('icon-link2', Link)
