// Generated by scripts/generate.mjs — do not edit by hand.
import { ListCross } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ListXIcon = createIcon('icon-list-x', ListCross)
