// Generated by scripts/generate.mjs — do not edit by hand.
import { Gps } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const LocateFixedIcon = createIcon('icon-locate-fixed', Gps)
