// Generated by scripts/generate.mjs — do not edit by hand.
import { LockKeyhole } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const LockKeyholeIcon = createIcon('icon-lock-keyhole', LockKeyhole)
