// Generated by scripts/generate.mjs — do not edit by hand.
import { Mailbox } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const MailboxIcon = createIcon('icon-mailbox', Mailbox)
