// Generated by scripts/generate.mjs — do not edit by hand.
import { LetterOpened } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const MailOpenIcon = createIcon('icon-mail-open', LetterOpened)
