// Generated by scripts/generate.mjs — do not edit by hand.
import { ChatRound } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const MessageCircleIcon = createIcon('icon-message-circle', ChatRound)
