// Generated by scripts/generate.mjs — do not edit by hand.
import { ChatSquare } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const MessageSquareIcon = createIcon('icon-message-square', ChatSquare)
