// Generated by scripts/generate.mjs — do not edit by hand.
import { Microphone } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const MicIcon = createIcon('icon-mic', Microphone)
