// Generated by scripts/generate.mjs — do not edit by hand.
import { Minimize } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const Minimize2Icon = createIcon('icon-minimize2', Minimize)
