// Generated by scripts/generate.mjs — do not edit by hand.
import { QuitFullScreen } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const MinimizeIcon = createIcon('icon-minimize', QuitFullScreen)
