// Generated by scripts/generate.mjs — do not edit by hand.
import { MinusCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const MinusCircleIcon = createIcon('icon-minus-circle', MinusCircle)
