// Generated by scripts/generate.mjs — do not edit by hand.
import { TransferVertical } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const MoveVerticalIcon = createIcon(
  'icon-move-vertical',
  TransferVertical,
)
