// Generated by scripts/generate.mjs — do not edit by hand.
import { StreetsNavigation } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const NavigationIcon = createIcon('icon-navigation', StreetsNavigation)
