// Generated by scripts/generate.mjs — do not edit by hand.
import { Sidebar } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const PanelLeftIcon = createIcon('icon-panel-left', Sidebar)
