// Generated by scripts/generate.mjs — do not edit by hand.
import { RulerPen } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const PencilRulerIcon = createIcon('icon-pencil-ruler', RulerPen)
