// Generated by scripts/generate.mjs — do not edit by hand.
import { IncomingCallRounded } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const PhoneIncomingIcon = createIcon(
  'icon-phone-incoming',
  IncomingCallRounded,
)
