// Generated by scripts/generate.mjs — do not edit by hand.
import { PieChart } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const PieChartIcon = createIcon('icon-pie-chart', PieChart)
