// Generated by scripts/generate.mjs — do not edit by hand.
import { Play } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const PlayIcon = createIcon('icon-play', Play)
