// Generated by scripts/generate.mjs — do not edit by hand.
import { PlayCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const PlayCircleIcon = createIcon('icon-play-circle', PlayCircle)
