// Generated by scripts/generate.mjs — do not edit by hand.
import { Power } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const PowerIcon = createIcon('icon-power', Power)
