// Generated by scripts/generate.mjs — do not edit by hand.
import { Printer } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const PrinterIcon = createIcon('icon-printer', Printer)
