// Generated by scripts/generate.mjs — do not edit by hand.
import { Radio } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const RadioIcon = createIcon('icon-radio', Radio)
