// Generated by scripts/generate.mjs — do not edit by hand.
import { Repeat } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const RepeatIcon = createIcon('icon-repeat', Repeat)
