// Generated by scripts/generate.mjs — do not edit by hand.
import { MultipleForwardLeft } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ReplyAllIcon = createIcon('icon-reply-all', MultipleForwardLeft)
