// Generated by scripts/generate.mjs — do not edit by hand.
import { Rocket } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const RocketIcon = createIcon('icon-rocket', Rocket)
