// Generated by scripts/generate.mjs — do not edit by hand.
import { Feed } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const RssIcon = createIcon('icon-rss', Feed)
