// Generated by scripts/generate.mjs — do not edit by hand.
import { Ruler } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const RulerIcon = createIcon('icon-ruler', Ruler)
