// Generated by scripts/generate.mjs — do not edit by hand.
import { FaceScanCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ScanFaceIcon = createIcon('icon-scan-face', FaceScanCircle)
