// Generated by scripts/generate.mjs — do not edit by hand.
import { EyeScan } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ScanEyeIcon = createIcon('icon-scan-eye', EyeScan)
