// Generated by scripts/generate.mjs — do not edit by hand.
import { ObjectScan } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ScanIcon = createIcon('icon-scan', ObjectScan)
