// Generated by scripts/generate.mjs — do not edit by hand.
import { Scooter } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ScooterIcon = createIcon('icon-scooter', Scooter)
