// Generated by scripts/generate.mjs — do not edit by hand.
import { Plain2 } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SendHorizontalIcon = createIcon('icon-send-horizontal', Plain2)
