// Generated by scripts/generate.mjs — do not edit by hand.
import { Plain } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SendIcon = createIcon('icon-send', Plain)
