// Generated by scripts/generate.mjs — do not edit by hand.
import { ShieldCross } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ShieldXIcon = createIcon('icon-shield-x', ShieldCross)
