// Generated by scripts/generate.mjs — do not edit by hand.
import { ShieldUser } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ShieldUserIcon = createIcon('icon-shield-user', ShieldUser)
