// Generated by scripts/generate.mjs — do not edit by hand.
import { ShieldPlus } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ShieldPlusIcon = createIcon('icon-shield-plus', ShieldPlus)
