// Generated by scripts/generate.mjs — do not edit by hand.
import { ShieldCheck } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ShieldCheckIcon = createIcon('icon-shield-check', ShieldCheck)
