// Generated by scripts/generate.mjs — do not edit by hand.
import { Shield } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ShieldIcon = createIcon('icon-shield', Shield)
