// Generated by scripts/generate.mjs — do not edit by hand.
import { CartLarge } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ShoppingBasketIcon = createIcon('icon-shopping-basket', CartLarge)
