// Generated by scripts/generate.mjs — do not edit by hand.
import { Bag } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ShoppingBagIcon = createIcon('icon-shopping-bag', Bag)
