// Generated by scripts/generate.mjs — do not edit by hand.
import { Shuffle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ShuffleIcon = createIcon('icon-shuffle', Shuffle)
