// Generated by scripts/generate.mjs — do not edit by hand.
import { SkipNext } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SkipForwardIcon = createIcon('icon-skip-forward', SkipNext)
