// Generated by scripts/generate.mjs — do not edit by hand.
import { SliderVertical } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SlidersVerticalIcon = createIcon(
  'icon-sliders-vertical',
  SliderVertical,
)
