// Generated by scripts/generate.mjs — do not edit by hand.
import { SliderHorizontal } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SlidersHorizontalIcon = createIcon(
  'icon-sliders-horizontal',
  SliderHorizontal,
)
