// Generated by scripts/generate.mjs — do not edit by hand.
import { Smartphone } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SmartphoneIcon = createIcon('icon-smartphone', Smartphone)
