// Generated by scripts/generate.mjs — do not edit by hand.
import { Snowflake } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SnowflakeIcon = createIcon('icon-snowflake', Snowflake)
