// Generated by scripts/generate.mjs — do not edit by hand.
import { Sofa } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SofaIcon = createIcon('icon-sofa', Sofa)
