// Generated by scripts/generate.mjs — do not edit by hand.
import { SlashSquare } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SquareSlashIcon = createIcon('icon-square-slash', SlashSquare)
