// Generated by scripts/generate.mjs — do not edit by hand.
import { CodeSquare } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SquareCodeIcon = createIcon('icon-square-code', CodeSquare)
