// Generated by scripts/generate.mjs — do not edit by hand.
import { ScissorsSquare } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SquareScissorsIcon = createIcon(
  'icon-square-scissors',
  ScissorsSquare,
)
