// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareAltArrowRight } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SquareChevronRightIcon = createIcon(
  'icon-square-chevron-right',
  SquareAltArrowRight,
)
