// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareArrowDown } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SquareArrowDownIcon = createIcon(
  'icon-square-arrow-down',
  SquareArrowDown,
)
