// Generated by scripts/generate.mjs — do not edit by hand.
import { SquareAltArrowLeft } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SquareChevronLeftIcon = createIcon(
  'icon-square-chevron-left',
  SquareAltArrowLeft,
)
