// Generated by scripts/generate.mjs — do not edit by hand.
import { Stars } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const StarsIcon = createIcon('icon-stars', Stars)
