// Generated by scripts/generate.mjs — do not edit by hand.
import { Stethoscope } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const StethoscopeIcon = createIcon('icon-stethoscope', Stethoscope)
