// Generated by scripts/generate.mjs — do not edit by hand.
import { StickerCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const StickerIcon = createIcon('icon-sticker', StickerCircle)
