// Generated by scripts/generate.mjs — do not edit by hand.
import { StopCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const StopCircleIcon = createIcon('icon-stop-circle', StopCircle)
