// Generated by scripts/generate.mjs — do not edit by hand.
import { Syringe } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const SyringeIcon = createIcon('icon-syringe', Syringe)
