// Generated by scripts/generate.mjs — do not edit by hand.
import { Tablet } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TabletIcon = createIcon('icon-tablet', Tablet)
