// Generated by scripts/generate.mjs — do not edit by hand.
import { Tag } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TagIcon = createIcon('icon-tag', Tag)
