// Generated by scripts/generate.mjs — do not edit by hand.
import { Telescope } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TelescopeIcon = createIcon('icon-telescope', Telescope)
