// Generated by scripts/generate.mjs — do not edit by hand.
import { Programming } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TerminalIcon = createIcon('icon-terminal', Programming)
