// Generated by scripts/generate.mjs — do not edit by hand.
import { TestTube } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TestTube2Icon = createIcon('icon-test-tube2', TestTube)
