// Generated by scripts/generate.mjs — do not edit by hand.
import { Like } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ThumbsUpIcon = createIcon('icon-thumbs-up', Like)
