// Generated by scripts/generate.mjs — do not edit by hand.
import { Stopwatch } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TimerIcon = createIcon('icon-timer', Stopwatch)
