// Generated by scripts/generate.mjs — do not edit by hand.
import { GraphUp } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TrendingUpIcon = createIcon('icon-trending-up', GraphUp)
