// Generated by scripts/generate.mjs — do not edit by hand.
import { GraphDown } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TrendingDownIcon = createIcon('icon-trending-down', GraphDown)
