// Generated by scripts/generate.mjs — do not edit by hand.
import { Turntable } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TurntableIcon = createIcon('icon-turntable', Turntable)
