// Generated by scripts/generate.mjs — do not edit by hand.
import { Tv } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const Tv2Icon = createIcon('icon-tv2', Tv)
