// Generated by scripts/generate.mjs — do not edit by hand.
import { Text } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const TypeIcon = createIcon('icon-type', Text)
