// Generated by scripts/generate.mjs — do not edit by hand.
import { TextUnderline } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UnderlineIcon = createIcon('icon-underline', TextUnderline)
