// Generated by scripts/generate.mjs — do not edit by hand.
import { UndoLeft } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UndoIcon = createIcon('icon-undo', UndoLeft)
