// Generated by scripts/generate.mjs — do not edit by hand.
import { LinkBroken } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UnlinkIcon = createIcon('icon-unlink', LinkBroken)
