// Generated by scripts/generate.mjs — do not edit by hand.
import { CloudUpload } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UploadCloudIcon = createIcon('icon-upload-cloud', CloudUpload)
