// Generated by scripts/generate.mjs — do not edit by hand.
import { UsbCircle } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UsbIcon = createIcon('icon-usb', UsbCircle)
