// Generated by scripts/generate.mjs — do not edit by hand.
import { UserMinus } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UserMinus2Icon = createIcon('icon-user-minus2', UserMinus)
