// Generated by scripts/generate.mjs — do not edit by hand.
import { UserCross } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UserX2Icon = createIcon('icon-user-x2', UserCross)
