// Generated by scripts/generate.mjs — do not edit by hand.
import { UserRounded } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UserRoundIcon = createIcon('icon-user-round', UserRounded)
