// Generated by scripts/generate.mjs — do not edit by hand.
import { UserCross } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const UserRoundXIcon = createIcon('icon-user-round-x', UserCross)
