// Generated by scripts/generate.mjs — do not edit by hand.
import { Videocamera } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const VideoIcon = createIcon('icon-video', Videocamera)
