// Generated by scripts/generate.mjs — do not edit by hand.
import { Volleyball } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const VolleyballIcon = createIcon('icon-volleyball', Volleyball)
