// Generated by scripts/generate.mjs — do not edit by hand.
import { Volume } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const VolumeIcon = createIcon('icon-volume', Volume)
