// Generated by scripts/generate.mjs — do not edit by hand.
import { VolumeLoud } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const Volume2Icon = createIcon('icon-volume2', VolumeLoud)
