// Generated by scripts/generate.mjs — do not edit by hand.
import { Muted } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const VolumeXIcon = createIcon('icon-volume-x', Muted)
