// Generated by scripts/generate.mjs — do not edit by hand.
import { Wind } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const WindIcon = createIcon('icon-wind', Wind)
