// Generated by scripts/generate.mjs — do not edit by hand.
import { Wineglass } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const WineIcon = createIcon('icon-wine', Wineglass)
