// Generated by scripts/generate.mjs — do not edit by hand.
import { Bolt } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ZapIcon = createIcon('icon-zap', Bolt)
