// Generated by scripts/generate.mjs — do not edit by hand.
import { MagniferZoomIn } from '@solar-icons/react-perf/Outline'

import { createIcon } from '../create-icon.js'

export const ZoomInIcon = createIcon('icon-zoom-in', MagniferZoomIn)
