// Generated by scripts/generate.mjs — do not edit by hand.

/** Where an icon's drawing comes from. */
export type IconSource =
  /** Hand-written name this package defines, independent of any other set. */
  | 'semantic'
  /** Named after `lucide-react`, drawn by Solar. */
  | 'lucide'
  /** Brand mark. Trademarks belong to their owners — see LICENSE-THIRD-PARTY. */
  | 'brand'

/**
 * What the icon depicts, taken from Solar's own grouping rather than a
 * taxonomy invented here — `brands` is the one group Solar has no say in.
 */
export type IconCategory =
  | 'arrows'
  | 'arrows-action'
  | 'astronomy'
  | 'brands'
  | 'building'
  | 'business'
  | 'call'
  | 'devices'
  | 'faces'
  | 'files'
  | 'folders'
  | 'food'
  | 'hands'
  | 'home'
  | 'it'
  | 'like'
  | 'list'
  | 'map'
  | 'medicine'
  | 'messages'
  | 'money'
  | 'nature'
  | 'notes'
  | 'notifications'
  | 'parts'
  | 'school'
  | 'search'
  | 'security'
  | 'settings'
  | 'shopping'
  | 'sports'
  | 'text-formatting'
  | 'time'
  | 'tools'
  | 'ui'
  | 'users'
  | 'video'
  | 'weather'

export type IconManifestEntry = {
  name: string
  source: IconSource
  category: IconCategory
}

/** Every category present in `iconManifest`, in the order a picker should list them. */
export const iconCategories: IconCategory[] = [
  'arrows',
  'arrows-action',
  'astronomy',
  'brands',
  'building',
  'business',
  'call',
  'devices',
  'faces',
  'files',
  'folders',
  'food',
  'hands',
  'home',
  'it',
  'like',
  'list',
  'map',
  'medicine',
  'messages',
  'money',
  'nature',
  'notes',
  'notifications',
  'parts',
  'school',
  'search',
  'security',
  'settings',
  'shopping',
  'sports',
  'text-formatting',
  'time',
  'tools',
  'ui',
  'users',
  'video',
  'weather',
]

/**
 * Every icon this package exports, for building pickers and catalogues.
 *
 * Import it from `@turystack/react-icons/manifest`; it is a separate entry
 * point so rendering a single icon never pulls in a list of all of them.
 */
export const iconManifest: IconManifestEntry[] = [
  {
    category: 'ui',
    name: 'AccessibilityIcon',
    source: 'lucide',
  },
  {
    category: 'medicine',
    name: 'ActivityIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'AddIcon',
    source: 'semantic',
  },
  {
    category: 'it',
    name: 'AirplayIcon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'AlarmClockIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'AlbumIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'AlertCircleIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'AlertOctagonIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'AlertTriangleIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'AlignCenterHorizontalIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'AlignCenterVerticalIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'AlignLeftIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'AlignRightIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'AppleColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'AppleIcon',
    source: 'brand',
  },
  {
    category: 'notes',
    name: 'ArchiveIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'ArmchairIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowDownCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowDownIcon',
    source: 'semantic',
  },
  {
    category: 'arrows',
    name: 'ArrowDownLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowDownLeftSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowDownRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowDownRightSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowDownSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowLeftCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowLeftIcon',
    source: 'semantic',
  },
  {
    category: 'arrows',
    name: 'ArrowLeftRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowLeftSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowRightCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowRightIcon',
    source: 'semantic',
  },
  {
    category: 'arrows',
    name: 'ArrowRightSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowUpCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowUpDownIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowUpIcon',
    source: 'semantic',
  },
  {
    category: 'arrows',
    name: 'ArrowUpLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowUpLeftSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowUpRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowUpRightSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ArrowUpSquareIcon',
    source: 'lucide',
  },
  {
    category: 'astronomy',
    name: 'AtomIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'AtSignIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'AudioLinesIcon',
    source: 'lucide',
  },
  {
    category: 'like',
    name: 'AwardIcon',
    source: 'lucide',
  },
  {
    category: 'school',
    name: 'BackpackIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'BadgeCheckIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'BalloonIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'BanIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'BanknoteIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'BarChartIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'BathIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'BatteryFullIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'BatteryIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'BatteryLowIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'BatteryMediumIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'BedIcon',
    source: 'lucide',
  },
  {
    category: 'notifications',
    name: 'BellIcon',
    source: 'semantic',
  },
  {
    category: 'notifications',
    name: 'BellOffIcon',
    source: 'lucide',
  },
  {
    category: 'notifications',
    name: 'BellRingIcon',
    source: 'lucide',
  },
  {
    category: 'sports',
    name: 'BikeIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'BitbucketColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'BitbucketIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'BlueskyColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'BlueskyIcon',
    source: 'brand',
  },
  {
    category: 'devices',
    name: 'BluetoothIcon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'BoldIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'BoltIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'BombIcon',
    source: 'lucide',
  },
  {
    category: 'medicine',
    name: 'BoneIcon',
    source: 'lucide',
  },
  {
    category: 'school',
    name: 'BookIcon',
    source: 'lucide',
  },
  {
    category: 'school',
    name: 'BookmarkIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'BoxIcon',
    source: 'lucide',
  },
  {
    category: 'school',
    name: 'BriefcaseIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'BugIcon',
    source: 'lucide',
  },
  {
    category: 'building',
    name: 'Building2Icon',
    source: 'lucide',
  },
  {
    category: 'parts',
    name: 'BusIcon',
    source: 'semantic',
  },
  {
    category: 'school',
    name: 'CalculatorIcon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'CalendarCheckIcon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'CalendarIcon',
    source: 'semantic',
  },
  {
    category: 'time',
    name: 'CalendarPlusIcon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'CalendarSearchIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'CameraIcon',
    source: 'semantic',
  },
  {
    category: 'devices',
    name: 'CardSimIcon',
    source: 'lucide',
  },
  {
    category: 'shopping',
    name: 'CartIcon',
    source: 'semantic',
  },
  {
    category: 'it',
    name: 'CastIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CatIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'ChartColumnIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'ChartIcon',
    source: 'semantic',
  },
  {
    category: 'business',
    name: 'ChartLineIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'ChartPieIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CheckCheckIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CheckCircle2Icon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CheckCircleIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CheckIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'CheckLineIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CheckSquare2Icon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CheckSquareIcon',
    source: 'lucide',
  },
  {
    category: 'food',
    name: 'ChefHatIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronDownCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronDownIcon',
    source: 'semantic',
  },
  {
    category: 'arrows',
    name: 'ChevronDownSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronLeftCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronLeftIcon',
    source: 'semantic',
  },
  {
    category: 'arrows',
    name: 'ChevronLeftSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronRightCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronRightIcon',
    source: 'semantic',
  },
  {
    category: 'arrows',
    name: 'ChevronRightSquareIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronsDownIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronsLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronsRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronsUpIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronUpCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'ChevronUpIcon',
    source: 'semantic',
  },
  {
    category: 'arrows',
    name: 'ChevronUpSquareIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CircleAlertIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleArrowDownIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleArrowLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleArrowOutUpRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleArrowRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleArrowUpIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CircleCheckBigIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CircleCheckIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleChevronDownIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleChevronLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleChevronRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'CircleChevronUpIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CircleHelpIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CircleMinusIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'CirclePauseIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'CirclePlayIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'CircleSlash2Icon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'CircleSlashIcon',
    source: 'lucide',
  },
  {
    category: 'astronomy',
    name: 'CircleStarIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'CircleStopIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'CircleUserIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'CircleUserRoundIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CircleXIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'ClapperboardIcon',
    source: 'lucide',
  },
  {
    category: 'notes',
    name: 'ClipboardCheckIcon',
    source: 'lucide',
  },
  {
    category: 'notes',
    name: 'ClipboardIcon',
    source: 'semantic',
  },
  {
    category: 'notes',
    name: 'ClipboardListIcon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'Clock2Icon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'Clock3Icon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'Clock4Icon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'Clock5Icon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'ClockIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'CloseIcon',
    source: 'semantic',
  },
  {
    category: 'weather',
    name: 'CloudCheckIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'CloudDownloadIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'CloudIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'CloudRainIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'CloudSunIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'CloudUploadIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'Code2Icon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'CodeIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'CodeSquareIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'CodeXmlIcon',
    source: 'lucide',
  },
  {
    category: 'food',
    name: 'CoffeeIcon',
    source: 'lucide',
  },
  {
    category: 'settings',
    name: 'CogIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'CommandIcon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'CompassIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'ContactIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CopyIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'CopyrightIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'CpuIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CreativeCommonsIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'CreditCardIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'CropIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CrossIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'CrownIcon',
    source: 'lucide',
  },
  {
    category: 'settings',
    name: 'DashboardIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'DatabaseIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'DeleteIcon',
    source: 'semantic',
  },
  {
    category: 'video',
    name: 'Disc3Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'DiscIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'DiscordColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'DiscordIcon',
    source: 'brand',
  },
  {
    category: 'medicine',
    name: 'DnaIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'DollarSignIcon',
    source: 'lucide',
  },
  {
    category: 'food',
    name: 'DonutIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'DownloadCloudIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'DownloadIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'DropletIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'DropletsIcon',
    source: 'lucide',
  },
  {
    category: 'sports',
    name: 'DumbbellIcon',
    source: 'lucide',
  },
  {
    category: 'astronomy',
    name: 'EarthIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'EditIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'EllipsisIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'EmailIcon',
    source: 'semantic',
  },
  {
    category: 'text-formatting',
    name: 'EraserIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'ErrorIcon',
    source: 'semantic',
  },
  {
    category: 'money',
    name: 'EuroIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'ExpandIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'ExternalLinkIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'EyeClosedIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'EyeIcon',
    source: 'semantic',
  },
  {
    category: 'security',
    name: 'EyeOffIcon',
    source: 'semantic',
  },
  {
    category: 'brands',
    name: 'FacebookColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'FacebookIcon',
    source: 'brand',
  },
  {
    category: 'video',
    name: 'FastForwardIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'FerrisWheelIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'FigmaIcon',
    source: 'lucide',
  },
  {
    category: 'files',
    name: 'FileArchiveIcon',
    source: 'lucide',
  },
  {
    category: 'files',
    name: 'FileCheck2Icon',
    source: 'lucide',
  },
  {
    category: 'files',
    name: 'FileCheckIcon',
    source: 'lucide',
  },
  {
    category: 'files',
    name: 'FileCode2Icon',
    source: 'lucide',
  },
  {
    category: 'files',
    name: 'FileCodeIcon',
    source: 'lucide',
  },
  {
    category: 'files',
    name: 'FileDownIcon',
    source: 'lucide',
  },
  {
    category: 'files',
    name: 'FileIcon',
    source: 'semantic',
  },
  {
    category: 'notes',
    name: 'FilePlusIcon',
    source: 'lucide',
  },
  {
    category: 'notes',
    name: 'FilesIcon',
    source: 'semantic',
  },
  {
    category: 'files',
    name: 'FileTextIcon',
    source: 'lucide',
  },
  {
    category: 'files',
    name: 'FileUpIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'FilmIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'FilterIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'FlagIcon',
    source: 'lucide',
  },
  {
    category: 'nature',
    name: 'FlameIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'FlashlightIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'FlipHorizontal2Icon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'FlipHorizontalIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'FlipVertical2Icon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'FlipVerticalIcon',
    source: 'lucide',
  },
  {
    category: 'folders',
    name: 'FolderCheckIcon',
    source: 'lucide',
  },
  {
    category: 'folders',
    name: 'FolderIcon',
    source: 'semantic',
  },
  {
    category: 'folders',
    name: 'FolderInputIcon',
    source: 'lucide',
  },
  {
    category: 'folders',
    name: 'FolderOpenIcon',
    source: 'lucide',
  },
  {
    category: 'folders',
    name: 'FolderPlusIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'ForwardIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'FuelIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'Gamepad2Icon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'GamepadIcon',
    source: 'lucide',
  },
  {
    category: 'parts',
    name: 'GaugeIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'GhostIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'GiftIcon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'GitBranchIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'GitHubColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'GitHubIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'GitLabColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'GitLabIcon',
    source: 'brand',
  },
  {
    category: 'ui',
    name: 'GlassesIcon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'Globe2Icon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'GlobeIcon',
    source: 'semantic',
  },
  {
    category: 'brands',
    name: 'GoogleColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'GoogleIcon',
    source: 'brand',
  },
  {
    category: 'ui',
    name: 'GripHorizontalIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'GripIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'GripVerticalIcon',
    source: 'lucide',
  },
  {
    category: 'hands',
    name: 'HandHeartIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'HardDriveIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'HashIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'HeadphonesIcon',
    source: 'lucide',
  },
  {
    category: 'like',
    name: 'HeartCrackIcon',
    source: 'lucide',
  },
  {
    category: 'like',
    name: 'HeartIcon',
    source: 'semantic',
  },
  {
    category: 'medicine',
    name: 'HeartPulseIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'HelpCircleIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'HelpIcon',
    source: 'semantic',
  },
  {
    category: 'time',
    name: 'HistoryIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'HomeIcon',
    source: 'semantic',
  },
  {
    category: 'building',
    name: 'HospitalIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'HotelIcon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'HourglassIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'HouseIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'IdCardIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'ImageIcon',
    source: 'semantic',
  },
  {
    category: 'video',
    name: 'ImagesIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'ImportIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'InboxIcon',
    source: 'lucide',
  },
  {
    category: 'astronomy',
    name: 'InfinityIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'InfoIcon',
    source: 'semantic',
  },
  {
    category: 'brands',
    name: 'InstagramColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'InstagramIcon',
    source: 'brand',
  },
  {
    category: 'text-formatting',
    name: 'ItalicIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'KeyboardIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'KeyIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'KeyRoundIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'KeySquareIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'LampFloorIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'LampIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'Laptop2Icon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'LaptopIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'Layers2Icon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'Layers3Icon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'LayersIcon',
    source: 'lucide',
  },
  {
    category: 'settings',
    name: 'LayoutDashboardIcon',
    source: 'lucide',
  },
  {
    category: 'settings',
    name: 'LayoutGridIcon',
    source: 'lucide',
  },
  {
    category: 'nature',
    name: 'LeafIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'LibraryIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'LightbulbIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'LineChartIcon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'Link2Icon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'Link2OffIcon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'LinkIcon',
    source: 'lucide',
  },
  {
    category: 'list',
    name: 'ListCheckIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'ListFilterIcon',
    source: 'lucide',
  },
  {
    category: 'list',
    name: 'ListIcon',
    source: 'lucide',
  },
  {
    category: 'list',
    name: 'ListMusicIcon',
    source: 'lucide',
  },
  {
    category: 'list',
    name: 'ListXIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'Loader2Icon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'LoaderCircleIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'LoaderIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'LoadingIcon',
    source: 'semantic',
  },
  {
    category: 'map',
    name: 'LocateFixedIcon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'LocateIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'LockIcon',
    source: 'semantic',
  },
  {
    category: 'security',
    name: 'LockKeyholeIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'LoginIcon',
    source: 'semantic',
  },
  {
    category: 'arrows-action',
    name: 'LogInIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'LogoutIcon',
    source: 'semantic',
  },
  {
    category: 'arrows-action',
    name: 'LogOutIcon',
    source: 'lucide',
  },
  {
    category: 'nature',
    name: 'LuggageIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'MagnetIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'MailboxIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'MailIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'MailOpenIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'MapIcon',
    source: 'semantic',
  },
  {
    category: 'map',
    name: 'MapPinIcon',
    source: 'semantic',
  },
  {
    category: 'map',
    name: 'MapPinMinusIcon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'MapPinPlusIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'MastodonColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'MastodonIcon',
    source: 'brand',
  },
  {
    category: 'arrows-action',
    name: 'Maximize2Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'MaximizeIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'MenuIcon',
    source: 'semantic',
  },
  {
    category: 'brands',
    name: 'MercadoPagoColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'MercadoPagoIcon',
    source: 'brand',
  },
  {
    category: 'messages',
    name: 'MessageCircleIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'MessageCircleMoreIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'MessageSquareIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'MessagesSquareIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'MessengerColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'MessengerIcon',
    source: 'brand',
  },
  {
    category: 'video',
    name: 'MicIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'MicrosoftColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'MicrosoftIcon',
    source: 'brand',
  },
  {
    category: 'arrows-action',
    name: 'Minimize2Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'MinimizeIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'MinusCircleIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'MinusIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'MinusSquareIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'MirrorRoundIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'MonitorIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'MonitorSmartphoneIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'MoonIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'MoreHorizontalIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'MoreIcon',
    source: 'semantic',
  },
  {
    category: 'devices',
    name: 'MouseIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'MoveHorizontalIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'MoveVerticalIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'Music2Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'Music3Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'Music4Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'MusicIcon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'NavigationIcon',
    source: 'lucide',
  },
  {
    category: 'notes',
    name: 'NotebookIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'OctagonAlertIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'PackageIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'PaintRollerIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'PaletteIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'PanelLeftIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'PaperclipIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'PauseCircleIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'PauseIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'PayPalColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'PayPalIcon',
    source: 'brand',
  },
  {
    category: 'messages',
    name: 'PencilIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'PencilLineIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'PencilRulerIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'PenIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'PenLineIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'PercentIcon',
    source: 'lucide',
  },
  {
    category: 'call',
    name: 'PhoneCallIcon',
    source: 'lucide',
  },
  {
    category: 'call',
    name: 'PhoneIcon',
    source: 'semantic',
  },
  {
    category: 'call',
    name: 'PhoneIncomingIcon',
    source: 'lucide',
  },
  {
    category: 'call',
    name: 'PhoneMissedIcon',
    source: 'lucide',
  },
  {
    category: 'call',
    name: 'PhoneOffIcon',
    source: 'lucide',
  },
  {
    category: 'call',
    name: 'PhoneOutgoingIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'PictureInPicture2Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'PictureInPictureIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'PieChartIcon',
    source: 'lucide',
  },
  {
    category: 'medicine',
    name: 'PillIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'PinIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'PinterestColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'PinterestIcon',
    source: 'brand',
  },
  {
    category: 'medicine',
    name: 'PipetteIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'PixColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'PixIcon',
    source: 'brand',
  },
  {
    category: 'video',
    name: 'PlayCircleIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'PlayIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'Plug2Icon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'PlugIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'PlugZapIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'PlusIcon',
    source: 'semantic',
  },
  {
    category: 'video',
    name: 'PodcastIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'PowerIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'PresentationIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'PrinterIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'ProjectorIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'QrCodeIcon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'RadarIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'RadioIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'ReceiptIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'RedditColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'RedditIcon',
    source: 'brand',
  },
  {
    category: 'arrows-action',
    name: 'Redo2Icon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'RedoIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'RefreshCcwIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'RefreshCwIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'RefreshIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'RemoveIcon',
    source: 'semantic',
  },
  {
    category: 'video',
    name: 'Repeat1Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'Repeat2Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'RepeatIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'ReplyAllIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'ReplyIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'RewindIcon',
    source: 'lucide',
  },
  {
    category: 'astronomy',
    name: 'RocketIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'RotateCcwIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'RotateCwIcon',
    source: 'lucide',
  },
  {
    category: 'map',
    name: 'RouteIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'RssIcon',
    source: 'lucide',
  },
  {
    category: 'tools',
    name: 'RulerIcon',
    source: 'lucide',
  },
  {
    category: 'astronomy',
    name: 'SatelliteIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'SaveIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'ScaleIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ScanEyeIcon',
    source: 'lucide',
  },
  {
    category: 'faces',
    name: 'ScanFaceIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ScanIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'ScissorsIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'ScissorsSquareIcon',
    source: 'lucide',
  },
  {
    category: 'parts',
    name: 'ScooterIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'ScreenShareIcon',
    source: 'lucide',
  },
  {
    category: 'search',
    name: 'SearchIcon',
    source: 'semantic',
  },
  {
    category: 'security',
    name: 'SecurityIcon',
    source: 'semantic',
  },
  {
    category: 'messages',
    name: 'SendHorizontalIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'SendIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'ServerIcon',
    source: 'lucide',
  },
  {
    category: 'settings',
    name: 'Settings2Icon',
    source: 'lucide',
  },
  {
    category: 'settings',
    name: 'SettingsIcon',
    source: 'semantic',
  },
  {
    category: 'ui',
    name: 'Share2Icon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'ShareIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ShieldAlertIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ShieldCheckIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ShieldCloseIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ShieldIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ShieldMinusIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ShieldPlusIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ShieldUserIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'ShieldXIcon',
    source: 'lucide',
  },
  {
    category: 'shopping',
    name: 'ShoppingBagIcon',
    source: 'lucide',
  },
  {
    category: 'shopping',
    name: 'ShoppingBasketIcon',
    source: 'lucide',
  },
  {
    category: 'shopping',
    name: 'ShoppingCartIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'ShrinkIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'ShuffleIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'SidebarIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'SignalColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'SignalIcon',
    source: 'brand',
  },
  {
    category: 'map',
    name: 'SignpostIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'SirenIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'SkipBackIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'SkipForwardIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'SlashIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'SlashSquareIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'SlidersHorizontalIcon',
    source: 'lucide',
  },
  {
    category: 'settings',
    name: 'SlidersIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'SlidersVerticalIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'SmartphoneIcon',
    source: 'lucide',
  },
  {
    category: 'faces',
    name: 'SmileIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'SnapchatColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'SnapchatIcon',
    source: 'brand',
  },
  {
    category: 'weather',
    name: 'SnowflakeIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'SofaIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'SortIcon',
    source: 'semantic',
  },
  {
    category: 'food',
    name: 'SoupIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'SparklesIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'SpeakerIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'SpotifyColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'SpotifyIcon',
    source: 'brand',
  },
  {
    category: 'arrows',
    name: 'SquareArrowDownIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareArrowDownLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareArrowDownRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareArrowLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareArrowRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareArrowUpIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareArrowUpLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareArrowUpRightIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'SquareCheckIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareChevronDownIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareChevronLeftIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareChevronRightIcon',
    source: 'lucide',
  },
  {
    category: 'arrows',
    name: 'SquareChevronUpIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'SquareCodeIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'SquareMinusIcon',
    source: 'lucide',
  },
  {
    category: 'messages',
    name: 'SquarePenIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'SquareScissorsIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'SquareSlashIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'SquareXIcon',
    source: 'lucide',
  },
  {
    category: 'like',
    name: 'StarIcon',
    source: 'semantic',
  },
  {
    category: 'weather',
    name: 'StarsIcon',
    source: 'lucide',
  },
  {
    category: 'medicine',
    name: 'StethoscopeIcon',
    source: 'lucide',
  },
  {
    category: 'faces',
    name: 'StickerIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'StopCircleIcon',
    source: 'lucide',
  },
  {
    category: 'shopping',
    name: 'StoreIcon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'StrikethroughIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'StripeColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'StripeIcon',
    source: 'brand',
  },
  {
    category: 'ui',
    name: 'SubtitlesIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'SuccessIcon',
    source: 'semantic',
  },
  {
    category: 'weather',
    name: 'SunIcon',
    source: 'semantic',
  },
  {
    category: 'weather',
    name: 'SunriseIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'SunsetIcon',
    source: 'lucide',
  },
  {
    category: 'medicine',
    name: 'SyringeIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'SystemThemeIcon',
    source: 'semantic',
  },
  {
    category: 'devices',
    name: 'TabletIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'TagIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'TargetIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'TelegramColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'TelegramIcon',
    source: 'brand',
  },
  {
    category: 'devices',
    name: 'TelescopeIcon',
    source: 'lucide',
  },
  {
    category: 'it',
    name: 'TerminalIcon',
    source: 'lucide',
  },
  {
    category: 'medicine',
    name: 'TestTube2Icon',
    source: 'lucide',
  },
  {
    category: 'medicine',
    name: 'TestTubeIcon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'TextIcon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'TextSelectionIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'ThermometerIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'ThreadsColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'ThreadsIcon',
    source: 'brand',
  },
  {
    category: 'like',
    name: 'ThumbsDownIcon',
    source: 'lucide',
  },
  {
    category: 'like',
    name: 'ThumbsUpIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'TicketIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'TikTokColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'TikTokIcon',
    source: 'brand',
  },
  {
    category: 'time',
    name: 'TimerIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'TornadoIcon',
    source: 'lucide',
  },
  {
    category: 'parts',
    name: 'TrainIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'Trash2Icon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'TrashIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'TrendingDownIcon',
    source: 'lucide',
  },
  {
    category: 'business',
    name: 'TrendingUpIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'TriangleAlertIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'TrophyIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'TruckIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'TurntableIcon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'Tv2Icon',
    source: 'lucide',
  },
  {
    category: 'devices',
    name: 'TvIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'TwitchColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'TwitchIcon',
    source: 'brand',
  },
  {
    category: 'text-formatting',
    name: 'TypeIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'UmbrellaIcon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'UnderlineIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'Undo2Icon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'UndoIcon',
    source: 'lucide',
  },
  {
    category: 'text-formatting',
    name: 'UnlinkIcon',
    source: 'lucide',
  },
  {
    category: 'security',
    name: 'UnlockIcon',
    source: 'semantic',
  },
  {
    category: 'weather',
    name: 'UploadCloudIcon',
    source: 'lucide',
  },
  {
    category: 'arrows-action',
    name: 'UploadIcon',
    source: 'semantic',
  },
  {
    category: 'it',
    name: 'UsbIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'User2Icon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserCheck2Icon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserCheckIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserCircle2Icon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserCircleIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserIcon',
    source: 'semantic',
  },
  {
    category: 'users',
    name: 'UserMinus2Icon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserMinusIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserPlus2Icon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserPlusIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserRoundCheckIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserRoundIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserRoundMinusIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserRoundPlusIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserRoundXIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UsersIcon',
    source: 'semantic',
  },
  {
    category: 'users',
    name: 'UsersRoundIcon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserX2Icon',
    source: 'lucide',
  },
  {
    category: 'users',
    name: 'UserXIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'VideoIcon',
    source: 'lucide',
  },
  {
    category: 'sports',
    name: 'VolleyballIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'Volume1Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'Volume2Icon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'VolumeIcon',
    source: 'lucide',
  },
  {
    category: 'video',
    name: 'VolumeXIcon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'Wallet2Icon',
    source: 'lucide',
  },
  {
    category: 'money',
    name: 'WalletIcon',
    source: 'semantic',
  },
  {
    category: 'video',
    name: 'WallpaperIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'Wand2Icon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'WandIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'WandSparklesIcon',
    source: 'lucide',
  },
  {
    category: 'home',
    name: 'WashingMachineIcon',
    source: 'lucide',
  },
  {
    category: 'time',
    name: 'WatchIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'WeChatColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'WeChatIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'WhatsAppColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'WhatsAppIcon',
    source: 'brand',
  },
  {
    category: 'it',
    name: 'WifiIcon',
    source: 'lucide',
  },
  {
    category: 'weather',
    name: 'WindIcon',
    source: 'lucide',
  },
  {
    category: 'food',
    name: 'WineIcon',
    source: 'lucide',
  },
  {
    category: 'ui',
    name: 'XCircleIcon',
    source: 'lucide',
  },
  {
    category: 'settings',
    name: 'XIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'XSocialColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'XSocialIcon',
    source: 'brand',
  },
  {
    category: 'ui',
    name: 'XSquareIcon',
    source: 'lucide',
  },
  {
    category: 'brands',
    name: 'YouTubeColorIcon',
    source: 'brand',
  },
  {
    category: 'brands',
    name: 'YouTubeIcon',
    source: 'brand',
  },
  {
    category: 'ui',
    name: 'ZapIcon',
    source: 'lucide',
  },
  {
    category: 'search',
    name: 'ZoomInIcon',
    source: 'lucide',
  },
  {
    category: 'search',
    name: 'ZoomOutIcon',
    source: 'lucide',
  },
]
